# Bloqueo para dnsmasq. Generado por AntiPhishingRD (2026-09-11T02:47:07.858Z).
# Inclúyelo con: conf-file=/ruta/a/este/archivo (o colócalo en /etc/dnsmasq.d/)
address=/02teste.cc/0.0.0.0
address=/1profitdeal.com/0.0.0.0
address=/abilityindisabilityindia.org/0.0.0.0
address=/abrdokersignc.cfd/0.0.0.0
address=/accurateonlinelogin.top/0.0.0.0
address=/activar588.royalwebhosting.net/0.0.0.0
address=/allegrolokalnie.nr-327439sm32.lol/0.0.0.0
address=/allegrolokalnie.pl74646.top/0.0.0.0
address=/api.cdn22.net/0.0.0.0
address=/banrsserrvsasresumined.royalwebhosting.net/0.0.0.0
address=/beseest.com/0.0.0.0
address=/buathaisushi.com/0.0.0.0
address=/carlislefi.com/0.0.0.0
address=/lively-fog-af49.pablosoftwareplus.workers.dev/0.0.0.0
address=/loop-lumen.com/0.0.0.0
address=/nextside.cfd/0.0.0.0
address=/pub-d21b4190a47f45628c828456f23dd66e.r2.dev/0.0.0.0
address=/software-gateway.click/0.0.0.0
address=/www.abelmomaroc.com/0.0.0.0
