# Bloqueo nativo para Unbound (sin módulo RPZ). Generado por AntiPhishingRD (2026-09-11T14:59:26.922Z).
# Inclúyelo en unbound.conf con: include: "/ruta/a/este/archivo"
local-zone: "02teste.cc." always_nxdomain
local-zone: "0rder-ver1f2345.com." always_nxdomain
local-zone: "1profitdeal.com." always_nxdomain
local-zone: "abilityindisabilityindia.org." always_nxdomain
local-zone: "abrdokersignc.cfd." always_nxdomain
local-zone: "accurateonlinelogin.top." always_nxdomain
local-zone: "activar588.royalwebhosting.net." always_nxdomain
local-zone: "adps.pro." always_nxdomain
local-zone: "allegrolokalnie.nr-327439sm32.lol." always_nxdomain
local-zone: "allegrolokalnie.pl74646.top." always_nxdomain
local-zone: "alphapicaficagency.com." always_nxdomain
local-zone: "api.cdn22.net." always_nxdomain
local-zone: "banrsserrvsasresumined.royalwebhosting.net." always_nxdomain
local-zone: "beseest.com." always_nxdomain
local-zone: "buathaisushi.com." always_nxdomain
local-zone: "carlislefi.com." always_nxdomain
local-zone: "cu.srijanajha.com.np." always_nxdomain
local-zone: "download.pocketbitcoindesktop.com." always_nxdomain
local-zone: "dropboxb3.duckdns.org." always_nxdomain
local-zone: "globalsupportupdate.top." always_nxdomain
local-zone: "iloveboats.st." always_nxdomain
local-zone: "killurself1337-cdn.doxbin.mom." always_nxdomain
local-zone: "lively-fog-af49.pablosoftwareplus.workers.dev." always_nxdomain
local-zone: "loop-lumen.com." always_nxdomain
local-zone: "loveher.dpdns.org." always_nxdomain
local-zone: "mail.quietsurfwi.help." always_nxdomain
local-zone: "nextside.cfd." always_nxdomain
local-zone: "pdf-editore.com." always_nxdomain
local-zone: "pdfmun.software." always_nxdomain
local-zone: "pub-d21b4190a47f45628c828456f23dd66e.r2.dev." always_nxdomain
local-zone: "qqwwaa.tos-cn-hongkong.volces.com." always_nxdomain
local-zone: "quietsurfwi.help." always_nxdomain
local-zone: "scooter.cozyvistany.com." always_nxdomain
local-zone: "software-gateway.click." always_nxdomain
local-zone: "www.abelmomaroc.com." always_nxdomain
